### ISSUE TITLE
Large memory consumption (spikes) by HTMLParser

### ISSUE THREAD

**Issue by dsanghan** [iabudiab/HTMLKit#10] opened 2017-03-30 07:52 UTC
If you load a lot of html into HTMLParser, it uses upwards of 500-600MB for parsing at peak. More autorelease pools need to be added. I found a couple of places that are the worst offenders:

```- (void)HTMLInsertionModeInBody:(HTMLToken *)token```

``` - (NSString *)innerHTML```

```HTMLTokenizer nextObject```

Also, for a high number of nodes, always creating ```NSMutableOrderedSet``` is not ideal - that uses about 40-50MB.

**Comment by iabudiab** [comment] 2017-03-31 15:25
@dsanghan Hey there, I'll take a look at the whole memory consumption situation this weekend. Thanks for reporting 👍

**Comment by iabudiab** [comment] 2017-04-09 19:05
@dsanghan Hey there, I have just pushed some fixes on the develop branch regarding memory consumption. I would appreciate it if you could test it again and report back if it has improved or not.

I have included only the most obvious fixes and I am working on refactoring the logic of the parser a bit, in order to improve both performance and memory consumption.

Having said that, I could not reproduce the spikes you described. I could monitor a steady increase in memory allocation but no spikes. Could you please describe your setup including the resources you've used, so that I could reproduce the behaviour more accurately?

**Comment by dsanghan** [comment] 2017-04-11 06:42
@iabudiab Here's a test html that used to cause pretty large spikes - hopefully this helps.

[test.txt](https://github.com/iabudiab/HTMLKit/files/912316/test.txt)

**Comment by iabudiab** [comment] 2017-04-11 20:51
@dsanghan Thanks for the test file. I'll make some tests with it and report back, I'll try to free up some time for it ;)

**Comment by iabudiab** [comment] 2017-04-24 22:21
@dsanghan Here is the breakdown of the memory consumption based on the file you've provided. I'll be focusing on the main 4 areas that cause the most consumption and I'll break them into 4 separate comments for clarity.

**Comment by iabudiab** [comment] 2017-04-24 22:22
## `HTMLDocument adpotNode:`

![adpot node](https://cloud.githubusercontent.com/assets/5612057/25356673/57e3e0d2-293b-11e7-8498-751368b8ff11.png)

**Poblem**
Adopting a node casuses the underlying `childNodes` collection to be allocated even if the node has children, which defies the purpose of the lazy allocation introduced in commit: [b693a60358dc352ad23ca9d1999b093c2c215ad4]

**Solution**
Only allocate `childNodes` collection when inserting child nodes.

**Comment by iabudiab** [comment] 2017-04-24 22:22
## Node Pre-Insertion validation

![preinsertion validation](https://cloud.githubusercontent.com/assets/5612057/25357407/f4bd0b20-293d-11e7-8083-56127c53f689.png)

**Problem**
I must admit that `NSStringFromSelector(_cmd)` is much more expensive than I've realized.

**Solution**
The memory used here is only an issue when the `HTMLKit` validations are activated, which is the default setting. Compiling with the `HTMLKIT_NO_DOM_CHECKS` flag could help, if you really do not want the validations.

Otherwise we could either cache the selector or just use `NSString` constants. I think I'll go with constants here. 

> This also affects all other inline validation methods.

**Comment by iabudiab** [comment] 2017-04-24 22:22
## End Tag parsing in Body

![end tag in body](https://cloud.githubusercontent.com/assets/5612057/25357992/235f6bb0-2940-11e7-8f5f-01a61aa85e49.png)

**Problems**

- Enumerators are exhausted via `allObjects` which allocates a new array of objects
- The `StackOfOpenElements` allocates new dictionaries for each call

**Comment by iabudiab** [comment] 2017-04-24 22:26
## Start Tag parsing in Body

![start tag in body](https://cloud.githubusercontent.com/assets/5612057/25361164/104f9952-294d-11e7-9b94-88823b4b84ac.png)

**Problems**

- Pre-Insertion validation
- Adopt Node
- `StackOfOpenElements`

**Comment by iabudiab** [comment] 2017-04-24 22:30
The first 3 issues should be fixed in  8379cee, 1cd1a91 and 47ec086 which also reduced the total allocation size from 75mb to 55mb

The `StackOfOpenElements` is a bit trickier. I'll post here again once I've optimized it.

**Comment by iabudiab** [comment] 2017-04-26 19:54
@dsanghan Hey again, I've just pushed the optimized code for the `StackOfOpenElements`

The total memory usage is down to 40mb instead of 75mb 🎉 
As a side effect the parsing performance increased by about 30% 😁 

I'll be releasing a new version soon. For now the improved version is here: 644c180

Thanks again for bringing this issue to my attention. I would appreciate it if you could give it a test and give me feedback 😉

**Comment by iabudiab** [comment] 2017-05-02 13:51
Just released version 2.0.6 with the previous fixes 🎉 

Should any other memory related issues arise, please feel free to reopen or create a new issue!

**Closed as completed by iabudiab** 2017-05-02 13:51 UTC
Labels: enhancement
